tdevPath: ../teaching-dev
expectedTdevBranch: main
trackedElements:
    - src: docusaurus.config.ts
      dst: docusaurus.config.ts
    - src: src/
      dst: src
    - src: packages/
      dst: packages
    - src: updateSync/
      dst: updateSync
    - src: tsconfig.tdev.json
      dst: tsconfig.json
    - src: .prettierrc
      dst: .prettierrc
    - src: .prettierignore
      dst: .prettierignore
    - src: vitest.config.ts
      dst: vitest.config.ts
    - src: static/bry-libs/
      dst: static/bry-libs
watchedElements:
    - .babel.config.js
    - package.json
    - .env.example
